services:
  db:
    image: postgres:17
    ports:
      - "${DATABASE_PORT}:5432"
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: "${DATABASE_HOST}"
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_USERNAME}"
    healthcheck:
      test: pg_isready -U ${DATABASE_USERNAME}
      timeout: 3s
      retries: 10

volumes:
  db_data:
